### ISSUE TITLE
bug: "cl is deprecated"  

### ISSUE THREAD

**Issue by florhizome** [mclear-tools/bespoke-themes#5] opened 2021-06-27 11:07 UTC
I already posted this under your reddit thread. 
I got a little bit confused which is why held up reporting, since I introduced a fix myself but still got other problems.
The first thing that actually happens when I load bespoke-themes with the declaration in  the manual is this

```
Warning (comp): bespoke-themes.el:67:11: Warning: Package cl is deprecated Disable showing Disable logging
Warning (comp): /home/flo/.emacs.d/straight/build/bespoke-themes/bespoke-themes.el: Error: Symbol's value as variable is void for 
Warning (comp): bespoke-light-theme.el:43:36: Warning: Package cl is deprecated 
Warning (comp): /home/flo/.emacs.d/straight/build/bespoke-themes/bespoke-light-theme.el: Error: Symbol's value as variable is void for 
Warning (comp): bespoke-dark-theme.el:43:36: Warning: Package cl is deprecated 
Warning (comp): /home/flo/.emacs.d/straight/build/bespoke-themes/bespoke-dark-theme.el: Error: Symbol's value as variable is void for 
```

Afterwards any input will just repeat  `Symbol's value as variable is void for `.
I don't know if this is anyhow related with issue #4, but just adding `(eval-when-compile (require 'cl-lib))` at the top of `bespoke-themes.el` will resolve the problem.

**Comment by mclearc** [comment] 2021-06-27 14:13
Are you using a recent version of the theme? I removed the dependency (in part because your pull-request pointed this out--thanks!) on cl. The cause was the `loop` function in the clean-mode-line function. I've also merged the light and dark themes into one file. I suggest you pull and update your local repo.

**Comment by florhizome** [comment] 2021-06-27 15:17
I tested it a few days ago; with the same "head" as now. I use straight.el by default which should update your master at least every time i star emacs.
I also wasn't quite sure if you had merged my request as i deleted it pretty soon, because i wanted to do some more testing.. as i said, the ivy issue, and i switched to 28 by installing the "guix" package manager, which handles emacs special, but partly made me unale to run a clean restart. Also, pretty new to this all, I definitely need to manage my notifications better in order to get updated on my actions and convos....

**Comment by mclearc** [comment] 2021-06-27 15:25
One thing I noticed today is that I had, by habit, put "master" as the branch on the example, though it is really "main" (git and github made this switch of standard names a little while ago and I haven't quite caught up. So please be sure you've got everything set correctly. With a clean emacs 28 I run ivy/counsel/swiper fine, and there should be no calls to cl in the current version (only cl-lib and subr-x, which are both called at the top of `bespoke-modeline.el`. 

EDIT: oh - and with straight I normally need to pull changes manually using `straight-pull-package` or `straight-pull-all`

**Comment by florhizome** [comment] 2021-06-27 17:35
I just downloaded it manually and loaded it without straight... same result. will try with -q flag in a second.

It's quite confusing since "for" is nowhere used in the package. Kind of an indirect dependency?
Yeah but the calls in bespoke-modeline.el aren't sufficient for the whole package right? 
While I'd find it important to understand the problem I don't really see why adding the line would be harmful.

**Comment by mclearc** [comment] 2021-06-27 20:25
I still can't reproduce this. The `for` is from the following (note `for` after `cl-loop`

```emacs-lisp
(defun clean-mode-line ()
  (interactive)
  (cl-loop for cleaner in mode-line-cleaner-alist
           do (let* ((mode (car cleaner))
                     (mode-str (cdr cleaner))
                     (old-mode-str (cdr (assq mode minor-mode-alist))))
                (when old-mode-str
                  (setcar old-mode-str mode-str))
                ;; major mode
                (when (eq mode major-mode)
                  (setq mode-name mode-str)))))
```

at the top of `bespoke-modeline.el` you should see the following:

```emacs-lisp
;;; Requirements

(eval-when-compile
  (require 'subr-x)
  (require 'cl-lib))
```

if you don't see that then you haven't pulled the updated repo (I put this in the file almost a month ago). Since I can't reproduce this I'm not going to make any other changes unless I need to :) But remember, you can call `cl-lib` in your own init file like this:

```emacs-lisp
(use-package cl-lib   :straight (:type built-in) :demand t)
```

**Comment by mclearc** [comment] 2021-07-08 18:23
I'm going to close this as resolved but let me know if you're still having trouble.

**Closed as completed by mclearc** 2021-07-08 18:23 UTC

**Comment by florhizome** [comment] 2021-07-14 14:43
Yeah I still do.... I recently just ran emacs –q for trying again. Thought about separating the modeline package but for now I’m cool with simple modeline and doing the headerline trick manually.

**Comment by mclearc** [comment] 2021-07-14 16:48
Sorry to hear you're still having trouble. I'm still not able to reproduce this bug (at least not since commit 87f0fe6). You might try the config below (save as `test.el`). When loaded with `emacs -q -l test.el` it loads perfectly on my emacs 28. So my suspicion is that either your repo is outdated or there is something else going wrong. 

```emacs-lisp
;;; Set Test Dir
;; Change this to where ever you want straight to clone & build packages
(defconst bespoke-test-dir "~/.emacs.d/.local/custom-themes/bespoke-themes/bespoke-test-dir"
  "Directory used for testing bespoke-themes.")
(when (not (file-exists-p bespoke-test-dir))
  (make-directory bespoke-test-dir t))

;;; Straight
;; use straight.el to install all packages
;; https://github.com/raxod502/straight.el
;; Don't check packages on startup
(setq straight-check-for-modifications '(check-on-save find-when-checking))
;; set branch
(setq straight-repository-branch "master")
;; set dir
(setq straight-base-dir bespoke-test-dir)
;; use use-package
(setq straight-use-package-by-default t)
;; Check all updates interactively
(setq straight-vc-git-auto-fast-forward nil)
;; see https://github.com/raxod502/straight.el/issues/757
(setq native-comp-deferred-compilation-deny-list nil)

;; bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" straight-base-dir))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;;; Use-Package
;; install use package
(straight-use-package 'use-package)
;; settings
(setq use-package-always-defer nil
      use-package-verbose t
      use-package-minimum-reported-time 0
      use-package-enable-imenu-support t
      use-package-always-ensure nil)

;;; Bespoke Theme

(use-package bespoke-themes
  :straight (:host github :repo "mclear-tools/bespoke-themes" :branch "main")
  :config
  ;; Set header line
  (setq bespoke-set-mode-line 'header)
  ;; Set mode line height
  (setq bespoke-set-mode-line-size 3)
  ;; Show diff lines in modeline
  (setq bespoke-set-git-diff-mode-line t)
  ;; Set mode-line cleaner
  (setq bespoke-set-mode-line-cleaner t)
  ;; Set evil cursor colors
  (setq bespoke-set-evil-cursors t)
  ;; Use mode line visual bell
  (setq bespoke-set-visual-bell t)
  ;; Set use of italics
  (setq bespoke-set-italic-comments t
        bespoke-set-italic-keywords t)
  ;; Set variable pitch
  (setq bespoke-set-variable-pitch t)
  ;; Set initial theme variant
  (setq bespoke-set-theme 'dark)
  ;; Load theme
  (load-theme 'bespoke t))
```

**Comment by florhizome** [comment] 2021-07-14 17:45
yeah I really don’t know either. I‘m getting a funky error at normal startup tied to Guix thats the only sure thing I can say. ... am going to check on that.
